blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Ask questions on Stack Overflow (preferred)
    url: https://stackoverflow.com/questions/tagged/wagtail
    about: Ask structured and fully-formed questions about Wagtail or about building a site with Wagtail
  - name: ðŸ™‹ Ask questions on Slack
    url: https://github.com/wagtail/wagtail/wiki/Slack
    about: Ask general questions about Wagtail or about building a site with Wagtail
